---
# Define the host you want to run the playbook in a file called hosts
# run "ansible-playbook play.yml -i hosts" from this directory
- hosts: localhost
  remote_user: root
  gather_facts: no
  pre_tasks:

      # - name: "USER | Creation de {{ user }}"
      #   user: 
      #     name: "{{ user}}"
      #     shell: /bin/bash
      # - name: USER | Cle SSH
      #   authorized_key:
      #   user: "{{ user }}"
      #   state: present
      #   key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      # - name: "USER | Sudoers {{ user }}"
      #   lineinfile:
      #     dest: /etc/sudoers
      #     state: present
      #     regexp: "^{{ user }}"
      #     line: '{{ user }} ALL=(ALL) NOPASSWORD: ALL'
      #     validate: 'visudo -cf %s'

    - name: Install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false

    # - name: APT | Update & Upgrade
    #   apt:
    #     upgrade: dist
    #     update_cache: yes

    - name: Gather Facts
      setup:

  vars:
    mattermost_version: 5.20.1
    postgres_version: 9.4

   # The user the mattermost process will run as. The group will match.
    mattermost_user: mattermost

   # These do not need to be edited.
    db_user: mmmost
    db_name: mattermost

   # Choose a secure password. It is recommended you create a random password using
   # an external utility.
    db_password: notReallyPassword

   # This is the email address you want to be attached to the letsencrypt certificate. It should be valid.
    cert_email_address: abc@123.com


    
  roles:
    #- firewall
    - postgres
    #- mattermost
    - letsencrypt
    - nginx
    - cron
